spring:
  application:
    name: monitoring_server
databases:
  databaseConfigs:
    postgres:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/mydb
      username: postgres
      password: postgres
  default: postgres